const SWR_KEYS = {
    GET_ALL_COUNTRIES_SEARCHBAR: 'GET_ALL_COUNTRIES_FOR_SEARCHBAR',
    RANDOM_COUNTRY_LOCATOR: 'GET_RANDOM_COUNTRY_FOR_COUNTRY_LOCATOR_GAME',
    RANDOM_COUNTRY_CAPITAL: 'GET_RANDOM_COUNTRY_FOR_COUNTRY_CAPITAL_GAME',
}

export default SWR_KEYS
